### ISSUE TITLE
Open of hashes with relative path fails

### ISSUE THREAD

**Issue by joachimmetz** [rjhansen/nsrlsvr#12]
nsrlsvr currently requires the path of the hashes file to be absolute. I opt to get and test the absolute path before daemonizing also see: https://github.com/rjhansen/nsrlsvr/issues/11

Also some suggestion on improving the error messaging:

https://github.com/rjhansen/nsrlsvr/blob/master/src/main.cc#L88

```
  if (not infile) {
    log(LogLevel::ALERT, "couldn't open hashes file " + hashes_location);
    exit(EXIT_FAILURE);
  }
```

Which results in:

```
./src/nsrlsvr -p 9120 -f ./hashes.txt 
daemon started
couldn't open hashes file ./hashes.txt
```

But this provides me no insight into why the file could not be opened. Also IMO `not infile` is less clear what it is checking than the equivalent `not infile.is_open()`.

I opt to change this to (or equiv):

```
  if (not infile.is_open()) {
    log(LogLevel::ALERT, "couldn't open hashes file " + hashes_location + " with error: " + strerror(errno));
    exit(EXIT_FAILURE);
  }
```

Which results in:

```
./src/nsrlsvr -p 9120 -f ./hashes.txt 
daemon started
couldn't open hashes file ./hashes.txt with error: No such file or directory
```

**Comment by rjhansen** [comment]
Only one request per ticket, please.  :)

Relative paths: this is the sort of thing that's easy to do badly, but which can be done correctly.  There are extremely good reasons to not allow daemons to use relative paths, but the path could be converted to absolute with realpath().  This one is a good idea, and I'll see about implementing it.

Better error reporting: there is no guarantee the C++ runtime will implement streams with C I/O, meaning we cannot rely on errno.  Better error reporting needs to happen but not like this.  I'll think about how to do it.

Code clarity: this is straight from Bjarne Stroustrup's style recommendations.  Not changing it.

**Comment by rjhansen** [comment]
Progress report: relative paths works for me now.  Need to kick on it for a while more before I check it into -master.  Expect by the end of the week.

Better error reporting: some improvement.  Still working on figuring out the clearest way to handle this.  Expect by end of the week.

**Comment by joachimmetz** [comment]
Sounds good, thanks

**Comment by rjhansen** [comment]
Fix has been checked into git, but not well-tested.  Use -master at your own risk, as always.  :)

**Comment by joachimmetz** [comment]
thx, will try and let you know if I run into things

**Comment by rjhansen** [comment]
Closed after three weeks.  I'm assuming the fix is acceptable.  :)
