### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thomaxxl** [rjhansen/nsrlsvr#14]
After building against boost_1_64_0 on ubuntu&, i get following error on startup:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed
Aborted (core dumped)

**Comment by rjhansen** [comment]
Looking into this.  Give me a day or so.

**Comment by rjhansen** [comment]
I haven't been able to recreate this.  Boost 1.64 is very recent: do you have it installed side-by-side with an earlier version of Boost?  Is it possible that you're compiling against one version of Boost, but at run-time it's finding another version?

**Comment by thomaxxl** [comment]
sorry, my mistake: it was still loading older boost lib
