### ISSUE TITLE
Update documentation to state nsrlupdate requires sudo

### ISSUE THREAD

**Issue by danielguardicore** [rjhansen/nsrlsvr#17]
The `nsrlupdate` program requires sudo permissions even if it's not installed under /usr/local/bin?

Could you update documentation to state that? 
Or alternatively, allow the server to not run as sudo but I understand that is more complicated

**Comment by bridgeythegeek** [comment]
Might this be writing the files to `/usr/local/share/nsrlsvr`?

On first run of `nsrlupdate`, I get:
```
$ nsrlupdate NSRLFile.txt
Traceback (most recent call last):
  File "/usr/local/bin/nsrlupdate", line 69, in <module>
    process_rds(argv[1])
  File "/usr/local/bin/nsrlupdate", line 45, in process_rds
    my_mkdir("/usr/local/share/nsrlsvr")
  File "/usr/local/bin/nsrlupdate", line 25, in my_mkdir
    makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/share/nsrlsvr'
```
Once the directory is created and you set the permissions as you'd like (e.g. your user can write to this directory), you probably won't need `sudo`.

**Comment by rjhansen** [comment]
Sorry for taking so long getting back to this.  @bridgeythegeek is correct: make sure you have permissions to the filesystem.  nsrlsvr does not require root: I run it non-rooted regularly.
