### ISSUE TITLE
Having trouble running nsrlsvr on Ubuntu14.04

### ISSUE THREAD

**Issue by botnag** [rjhansen/nsrlsvr#6]
I've tried to follow the instructions here: https://github.com/rjhansen/nsrlsvr/blob/master/INSTALL
and so far have had no luck getting nsrlsvr to start on my Ubuntu64 Server 14.04 distro after configuring and installing via the make file.

    Finally, start nsrlsvr by something like:
    
    $ nsrlsvr -t 1800

After running that command nothing appears to happen, and I check running processes and there is no sign of the nsrlsvr process which suggests it never successfully ran.

I have two hashsets, one is a reduced custom RDS set created from latest in a zip file, where I used

    $ sudo nsrlupdate /home/rjh/Downloads/rds_244m.zip

and this command executed without any errors.

The other is the minimal RDS set where I tried to set by

    $ nsrlsvr -f /home/usr/NSRLFile.txt

 according to the nsrlsvr help 

    -f : specify an alternate RDS (default: /usr/local/share/nsrlsvr/NSRLFile.txt")

I have also tried nsrlsvr version 1.3.1 and again had no response when trying to start the server.

Could you please advise what I am doing wrong?

**Comment by rjhansen** [comment]
> https://github.com/rjhansen/nsrlsvr/blob/master/INSTALL

Those instructions are out of date for -master, but should still be accurate for the last released version.

> and so far have had no luck getting nsrlsvr to start on my Ubuntu64
> 14.04 distro.

What does the syslog say?  If nsrlsvr aborts at launch it displays an error message there, like any well-behaved daemon.  :)

**Comment by botnag** [comment]
Thanks for the instruction, it would appear the cause is the hash file supposedly being corrupt.
When I tried to use the minimal RDS hashset: 
Feb  4 15:43:22 ubuntu nsrlsvr: daemon started
Feb  4 15:43:22 ubuntu nsrlsvr: hash file appears corrupt!  Loading no hashes.
Feb  4 15:43:22 ubuntu nsrlsvr: offending line is #1
Feb  4 15:43:22 ubuntu nsrlsvr: offending line has 86 bytes
Feb  4 15:43:22 ubuntu nsrlsvr: Content follows:
Feb  4 15:43:22 ubuntu nsrlsvr: "SHA-1","MD5","CRC32","FileName","FileSize","ProductCode","OpSystemCode","SpecialCode"
Feb  4 15:43:22 ubuntu nsrlsvr: shutting down!

With this minimal set however (approx 2.5GB), it was downloaded from http://www.nsrl.nist.gov/Downloads.htm and no modifications were made to the file before I tried to use it (I noticed that it's no longer directly linked from the page). Is the problem here the first 'line' show headers?

**Comment by rjhansen** [comment]
There's your problem, then.  The minimal RDS dataset uses a different data format than nsrlsvr uses.

The hash file nsrlsvr uses is just a series of uppercase MD5 hashes (or, basically, the regex "^[A-F0-9]{32}$").

**Comment by botnag** [comment]
Ah okay thanks.

**Comment by rjhansen** [comment]
If you've been using the latest git sources, try again -- there was a bug in the nsrlupdate script (which was not present in prior versions).  It's almost ready for a 1.5 release.  This may work better for you, it may not.

If it helps, I just built nsrlsvr from git sources, using RDS 2.46m, on an Ubuntu 14.10 box.  Works fine, once I fixed that bug in nsrlupdate.  :)

**Comment by rjhansen** [comment]
And if you need, I can probably put together a .deb to install from.  Let me know.

**Comment by botnag** [comment]
I just tried the latest again and this what I see when trying to install: 

    admin@ubuntu:~/nsrlsvr-master$ make && sudo make install
    make  all-recursive
    make[1]: Entering directory `/home/admin/nsrlsvr-master'
    Making all in src
    make[2]: Entering directory `/home/libotong/nsrlsvr-master/src'
         CXX      nsrlsvr-main.o
    g++: error: @PTHREAD_CFLAGS@: No such file or directory
    make[2]: *** [nsrlsvr-main.o] Error 1
    make[2]: Leaving directory `/home/admin/nsrlsvr-master/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/admin/nsrlsvr-master'
    make: *** [all] Error 2

It seems like I'm missing some files?
