### ISSUE TITLE
Add an option to provide for a non-daemon mode

### ISSUE THREAD

**Issue by joachimmetz** [rjhansen/nsrlsvr#9]
It is currently hard to troubleshoot nsrlsvr, please add an option to provide for a non-daemon mode

**Comment by rjhansen** [comment]
Daemonization has very little to do with troubleshooting.  What you want is better error reporting/logging, which can be added without including a non-daemonized option.  Closing as a WONTFIX, at least for now.

**Comment by joachimmetz** [comment]
What I meant is what you propose in https://github.com/rjhansen/nsrlsvr/issues/11. Closing this one sounds good.
